config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  resources :movies
  resources :reviews
  resources :users
  get "signup" => "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }

  RATINGS = ["G", "PG", "PG-13", "R", "NC-17"]
  validates :rating, inclusion: { in: RATINGS }

  def self.released
    where("released_on < ?", Time.now).order("released_on desc")
  end

  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :email, email: true, uniqueness: {case_sensitive: false}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.released
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
      else
        render :new, status: :unprocessable_entity
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    # params[:movie].permit(:title, :description, :rating, :released_on, :total_gross) or
    # params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross) or
    # movie_params = params.require(:movie).permit!
    @movie.update(movie_params)
    if @movie.save
      flash[:notice] = "Movie sucessfully updated!"
      redirect_to @movie
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_path, status: :see_other, alert: "Movie successfully deleted!"
  end

  private

  def movie_params
    params.require(:movie).
      permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account updated!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, status: :see_other, alert: "Account deleted"
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to @user, notice: "Signed Up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    if movie.flop?
      "FLOP!!"
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  def year_of(movie)
    movie.released_on.year
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  Version 1
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "All Movies", movies_path, class: "button" %>
        <%= link_to "Add new movie", new_movie_path, class: "button" %>
      </li>
    </ul>
    <ul class="right">
      <li>
        <%= link_to "Sign Up", signup_path, class: "button" %>
        <%= link_to "Sign In", root_path, class: "button" %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "layouts/header" %>

<div class="content">
  <%= render 'layouts/flash' %>

  <%= yield %>
</div>

<%= render "layouts/footer" %>
</body>


</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f| %>
  <%= render "shared/errors", object: movie %>
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>
  <%= f.label :description %>
  <%= f.text_field :description, rows: 7 %>
  <%= f.label :rating %>
  <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
  <%= f.label :released_on %>
  <%= f.date_select :released_on, {}, { class: "date" } %>
  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>
  <%= f.label :director %>
  <%= f.text_field :director %>
  <%= f.label :duration %>
  <%= f.text_field :duration %>
  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing "<%= @movie.title %>"...</h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Add new movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
  <%= link_to "Delete", movie_path(@movie), class: "button", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this movie?"} %>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>Opps! Your form could not be saved.</h2>
    <h3>Please correct the following
        <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h3>Editing <%= @user.name %>...</h3>

<%= render 'form', user:@user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<% @users.each do |user| %>
  <div>
    <%= link_to user.name, user %>
    created
    <%= time_ago_in_words(user.created_at) %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
</section>

<div class="actions">
  <%= link_to "Edit", edit_user_path(@user), class: "button edit" %>
  <%= link_to "Delete", @user, data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }, class: "button edit" %>
</div>